const randomQuotes = [
  "Success is a journey, not a destination.",
  "Dreams demand hustle.",
  "Courage begins where comfort ends.",
  "Life’s too short for bad coffee.",
  "Creativity is intelligence having fun.",
  "You miss 100% of the shots you don’t take.",
  "Kindness is a language everyone understands.",
  "The best way out is always through.",
  "Don’t wait for opportunity. Create it.",
  "Failure is just feedback in disguise.",
  "Be the energy you want to attract.",
  "A smooth sea never made a skilled sailor.",
  "Happiness is homemade.",
  "The only limit is your imagination.",
  "Progress, not perfection.",
  "Stay curious. It’s contagious.",
  "Every expert was once a beginner.",
  "Turn your wounds into wisdom.",
  "Do more things that make you forget to check your phone.",
  "The future belongs to the brave.",
  "Success tastes better after struggle.",
  "Your vibe attracts your tribe.",
  "Make it happen. Shock everyone.",
  "Don’t count the days. Make the days count.",
  "You are your only limit.",
  "Small steps lead to big changes.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Mistakes are proof you’re trying.",
  "The best revenge is massive success.",
  "Live less out of habit, more out of intent.",
  "Stars can’t shine without darkness.",
  "If not now, when?",
  "Be so good they can’t ignore you.",
  "Your story matters.",
  "The comeback is always stronger than the setback.",
  "You are enough.",
  "Work hard in silence. Let success make the noise.",
  "Don’t just exist. Live.",
  "Stay hungry. Stay foolish.",
  "The best view comes after the hardest climb.",
  "You’re one decision away from a totally different life.",
  "Do it with passion or not at all.",
  "Life begins at the edge of your comfort zone.",
  "You don’t find the happy life. You make it.",
  "Be a voice, not an echo.",
  "The secret of getting ahead is getting started.",
  "Your dreams don’t work unless you do.",
  "Don’t be afraid to fail. Be afraid not to try.",
  "Success is built on discipline.",
  "You are the author of your own story.",
  "Let your faith be bigger than your fear.",
  "The harder you work, the luckier you get.",
  "Life is tough, but so are you.",
  "You were born to stand out.",
  "Start where you are. Use what you have. Do what you can.",
  "Be the change you wish to see.",
  "Your potential is endless.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "The only way to do great work is to love what you do.",
  "Success is the sum of small efforts repeated daily.",
  "You’ve got this.",
  "Believe you can and you’re halfway there.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never came from comfort zones.",
  "Don’t stop until you’re proud.",
  "The best dreams happen when you’re awake.",
  "You are stronger than you think.",
  "Make your life a masterpiece.",
  "Doubt kills more dreams than failure ever will.",
  "Your attitude determines your direction.",
  "Don’t wait for inspiration. Be the inspiration.",
  "You didn’t come this far to only come this far.",
  "Life is a daring adventure or nothing at all.",
  "Be bold. Be brave. Be you.",
  "Success starts with self-belief.",
  "You are the spark. Light it up.",
  "Don’t let fear decide your future.",
  "Live with purpose.",
  "The best is yet to come.",
  "You’re capable of amazing things.",
  "Make today count.",
  "Be relentless in your pursuit of greatness.",
  "Your time is now.",
  "Stay focused and never give up.",
  "You’re building something incredible.",
  "Let your dreams be bigger than your fears.",
  "You are unstoppable.",
  "Take the risk or lose the chance.",
  "Be the hero of your own story.",
  "Success is a series of small wins.",
  "You’re not too late. You’re right on time.",
  "Make your mark.",
  "You’re writing your legacy every day.",
  "Don’t just chase dreams. Catch them.",
  "You are a work in progress and a masterpiece at the same time.",
  "Live loud. Love louder.",
  "You’re the magic. Own it.",
  "Rise. Grind. Repeat.",
  "Be the storm that breaks the silence.",
  "Your greatness is waiting.",
  "You’re the reason someone believes in good.",
  "Go the extra mile. It’s never crowded.",
  "You’re a force to be reckoned with.",
  "Make it legendary."
];


let button = document.querySelector('button');
console.log(button);
let container = document.querySelector('#container');
console.log(container);


button.addEventListener('click', ()=>
{
    let index = Math.floor(Math.random()*100);
    container.textContent = randomQuotes[index];
})